// <auto-generated />
namespace ShipBobOrders.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class User_full_name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_full_name));
        
        string IMigrationMetadata.Id
        {
            get { return "201708151930368_User_full_name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
